// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import(
"github.com/gogf/gf/os/gtime"
)


// Category is the golang structure for table category.
type Category struct {
    CategoryId  string `orm:"category_id" json:"categoryId"`  //   
    Title       string `orm:"title"       json:"title"`       //   
    OwnerId     string `orm:"owner_id"    json:"ownerId"`     //   
    Description string `orm:"description" json:"description"` //   
}


// Note is the golang structure for table note.
type Note struct {
    NoteId      string      `orm:"note_id"      json:"noteId"`      //   
    Title       string      `orm:"title"        json:"title"`       //   
    Content     string      `orm:"content"      json:"content"`     //   
    CreatedAt   *gtime.Time `orm:"created_at"   json:"createdAt"`   //   
    UpdatedAt   *gtime.Time `orm:"updated_at"   json:"updatedAt"`   //   
    OwnerId     string      `orm:"owner_id"     json:"ownerId"`     //   
    CategoryId  string      `orm:"category_id"  json:"categoryId"`  //   
    Shared      bool        `orm:"shared"       json:"shared"`      //   
    Trash       bool        `orm:"trash"        json:"trash"`       //   
    DeletedTime *gtime.Time `orm:"deleted_time" json:"deletedTime"` //   
}


// Plan is the golang structure for table plan.
type Plan struct {
    PlanId    string      `orm:"plan_id"    json:"planId"`    //   
    Title     string      `orm:"title"      json:"title"`     //   
    Content   string      `orm:"content"    json:"content"`   //   
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //   
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //   
    Completed bool        `orm:"completed"  json:"completed"` //   
    OwnerId   string      `orm:"owner_id"   json:"ownerId"`   //   
}


// User is the golang structure for table user.
type User struct {
    UserId    string      `orm:"user_id"    json:"userId"`    //   
    Email     string      `orm:"email"      json:"email"`     //   
    Password  string      `orm:"password"   json:"password"`  //   
    FullName  string      `orm:"full_name"  json:"fullName"`  //   
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //   
}