// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CloudNote/app/dao/internal"
)

// noteDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type noteDao struct {
	*internal.NoteDao
}

var (
	// Note is globally public accessible object for table note operations.
	Note = noteDao{
		internal.NewNoteDao(),
	}
)

// Fill with you ideas below.